global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: kirmya-api
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8080"]
        labels:
          service: kirmya

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
